joint_state_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 250

joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - phantomx_pincher_arm_shoulder_pan_joint
    - phantomx_pincher_arm_shoulder_lift_joint
    - phantomx_pincher_arm_elbow_flex_joint
    - phantomx_pincher_arm_wrist_flex_joint

gripper_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - phantomx_pincher_gripper_finger1_joint
    - phantomx_pincher_gripper_finger2_joint
